# crawler-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webcrawler
spec:
  selector:
    matchLabels:
      app: webcrawler
  replicas: 1
  template:
    metadata:
      labels:
        app: webcrawler
    spec:
      containers:
      - name: webcrawler
        image: webcrawler
        ports:
        - containerPort: 80
        env:
        - name: MONGO_HOST
          value: "mongodb"
        - name: MONGO_PORT
          value: "27017"
        - name: MONGO_USER
          value: "adminUser"
        - name: MONGO_PASS
          value: "adminPassword"
      imagePullSecrets:
      - name: docker-login