version: '4.31'
services:
  webcrawler:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "8090:8000"
    # networks:
    #   - my_network

    depends_on:
      - mongodb
      - rabbitmq
    environment:
      MONGO_URL: "mongodb://mongodb:27017/webcrawler"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: 77222378
    # networks:
    #   - my_network


  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - "27018:27017"
    # networks:
    #   - my_network
    environment:
      MONGO_INITDB_ROOT_USERNAME: adminUser  # نام کاربری ادمین
      MONGO_INITDB_ROOT_PASSWORD: 77222378  # رمز عبور ادمین
      MONGO_INITDB_DATABASE: crawler
  nginx:
    image: nginx
    depends_on:
      - webcrawler
      - rabbitmq
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
#     networks:
#       - my_network
# networks:
#   my_network:
#     driver: bridge