apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: webcrawler-webcrawler
  name: webcrawler-webcrawler
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: webcrawler-webcrawler
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: webcrawler-webcrawler
    spec:
      containers:
        - env:
            - name: MONGO_URL
              value: mongodb://mongodb:27017/webcrawler-webcrawler
          image: webcrawler-webcrawler
          name: webcrawler-webcrawler
          ports:
            - containerPort: 8091
              protocol: TCP
      restartPolicy: Always
